# Basic server properties
server:
  port: ${FILE_PORT:9003}

# Basic spring properties
spring:
  # Application
  application:
    name: ${FILE_APPLICATION_NAME:file-service}

# Basic actuator properties
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:*}
  endpoint:
    health:
      show-details: ${ACTUATOR_HEALTH_SHOW_DETAILS:always}